### ISSUE TITLE
[FrontEnd] The webapp isn't responsive for mobile (425px)

### ISSUE THREAD

**Issue by apurv-1** [apurv-1/Foodgram#2]
The current web app isn't responsive for devices with screen size less than 425px.(Mobiles)

**Comment by SANTHOSH17-DOT** [comment]
Can I work on this issue??

**Comment by apurv-1** [comment]
> Can I work on this issue??

I've updated the readme with steps for how to run the project locally. Do let me know if you still face any issues.

**Comment by Dinesh9350** [comment]
i want to work on this issue
