### ISSUE TITLE
Readme error

### ISSUE THREAD

**Issue by SANTHOSH17-DOT** [apurv-1/Foodgram#3]
![image](https://user-images.githubusercontent.com/74037707/136518322-5baa5100-ddef-4811-b1d0-cbfcfba0925b.png)

It's `npm start ` for running the server right?? in REAME.md
@apurv-1

**Comment by apurv-1** [comment]
> REA

It's a typo, you can either use `npm start` or `node myapp.js`.

**Comment by apurv-1** [comment]
git
